### ISSUE TITLE
Peer Dependencies are Being Deprecated

### ISSUE THREAD

**Issue by Saajan** [newtriks/generator-react-webpack#126]
Its already showing warning while installing .. npm@3 beta is released and it doesnt support Peer Dependencies

**Comment by weblogixx** [comment]
@saajan: We are aware of this problem. We have created a new version of the generator (starting at 2.0) that will be released in a couple of hours. This version does not use the currents underlyings and does also not use peerDependencies anymore. However because we will phase out the Version 1 of the generator, I think we wont need to fix it in this version.

If you (or other persons) need this fixed in 1.0, you are more than welcome to open a new issue and submit a pull request.
