### ISSUE TITLE
Looking for contributers

### ISSUE THREAD

**Issue by newtriks** [newtriks/generator-react-webpack#129]
I've been pretty busy for a while now and unable to dedicate as much time to this generator as I would like (or is needed). If anyone is interested in help contribute please email me simon at newtriks dot com.

**Comment by weblogixx** [comment]
@newtriks: Sorry mate, was on vacation and could not answer your last mail. I would be very happy to help you out as a contributor. I also have some plans that I am investigating in currently:

- ES2015 support for generated components (Unit-Tests have this support since the last release)
- Reduction of Flux-Frameworks (have to think about how we could implement this on a module base)
- Overall reduction of complexity

Still need to think about how to integrate this stuff. Suggestions?

**Comment by newtriks** [comment]
@weblogixx absolutely no problem mate. In regards to your comments see https://github.com/newtriks/generator-react-webpack/issues/130, I'm mulling of potential approaches for this...

**Comment by weblogixx** [comment]
Maybe composeability would be an option? (Never tried it myself). https://github.com/yeoman/yeoman.io/blob/master/app/authoring/composability.md

**Comment by newtriks** [comment]
@weblogixx gonna move this conversation over to https://github.com/newtriks/generator-react-webpack/issues/130 :+1:

**Comment by weblogixx** [comment]
Think this can be closed for now :)
