### ISSUE TITLE
Remove Flux, Reflux, etc from generator

### ISSUE THREAD

**Issue by newtriks** [newtriks/generator-react-webpack#130]
The generator has gained much more traction than I would have invisaged and to maintain it better I need to remove complexity and additional potentially unnecessary functionality.

A while back I merged in a pull request that introduced Flux and Reflux. Although the input was appreciated it has increased the overall scope of this generator, has confusing directory naming conventions (*a*, *c*, *s*) and with the growth of the options to develop with React, the additions could become endless. I should have paid more attention and had more forethought, however, I simply have not had the time to focus as I wanted on this generator.

I am going to start looking at removing all the unnecessary framework related bloat and hopefully someone in the community can separately write their own generators for them.

**Comment by newtriks** [comment]
@weblogixx in regards to your suggestion https://github.com/newtriks/generator-react-webpack/issues/129#issuecomment-123608007 that looks great. My suggested plan of attack is to:

1. Strip back the generator to the original bare bones of functionality.
2. Update all packages both in templates and generator.
3. Fix existing issues related to core generated project.
4. Optimise for ES2015, etc.
5. Create a new release and merge back into master.
6. Focus on composing with other generators.

**Comment by weblogixx** [comment]
@newtriks Sounds good to me. So, first step would be to remove the flux stuff. What do you think about putting those changes in its own branch so we can still supply bugfixes for the current version in the trunk? Just added a new "slimdown" branch on my fork where i will remove flux and all of its traces.

**Comment by newtriks** [comment]
@weblogixx done: https://github.com/newtriks/generator-react-webpack/tree/v1

**Comment by weblogixx** [comment]
@newtriks: I think I have a good working version done in v1. Mind to take a look and tell me if you find something you dont like? We then should plan how to migrate to the new version (should then be 2.0 because breaking changes?)

**Comment by newtriks** [comment]
@weblogixx awesome work mate thank you! My thoughts so far are:

1. Not sure what [this](https://github.com/newtriks/generator-react-webpack/tree/v1/c) is about as the directory naming of simply `c` is unclear?
2. I think we could get rid of Grunt completely also and have that as a sub-generator. We could have all the necessary logic for running webpack etc using npm scripts in the [package.json](https://github.com/newtriks/generator-react-webpack/blob/v1/templates/common/_package.json). What do you think?
3. I'd use ES2015/2016 module imports and destructuring in the JS, for example [here](https://github.com/newtriks/generator-react-webpack/blob/v1/templates/javascript/App.js).

What do you think?

**Comment by weblogixx** [comment]
Hi,

gonna look for this stuff in a couple of days. I think tge "c" directory is a nice shortcut as it allows to use yo react-webpack:c newcomponent, saves a view keystrokes.

**Comment by newtriks** [comment]
I will try also to dive in if I get a chance

**Comment by weblogixx** [comment]
@newtriks: I recently played around with webpack and react, as well as a little unit testing (not finished at the moment). You can see it at https://github.com/weblogixx/react-webpack-template. All scripts use npm as runner, so there is no more grunt/gulp/whatever involved.

I still use karma as a unit runner, because it allows you to test events and other stuff. Even if it is slow, I think it is a good approach for the moment (at least until shallow rendering is fully implemented with all stuff that is missing from there. Also I had some problems with it (like testing components that get wrapped in AltContainers), so it does not seem that it is useable without any problems in the moment. When using karma, one could still use the "old" ReactTestUtils if needed, using the shallowRenderer only for "dumb" components that have no state but just do plain rendering.

Seems like it is not so easy to test react yet :(.

Please tell me what you think about the template, if it is acceptable for you, I will include it into the v1 branch.

**Comment by newtriks** [comment]
Hey @weblogixx, thanks for this mate. I agree that Karma although slow is still maybe the better option. I started playing with some testing basics [here](https://github.com/eggheadio/egghead-react-unit-testing/blob/master/test/ArtistSpec.js). There are also some inspiration to be gained from [this](https://github.com/gaearon/react-dnd) codebase I think.

**Comment by weblogixx** [comment]
Hi @newtriks, I got the next version ready. It only includes the basic react component creation (as usually with Stylesheet and Testsupport. You can test it at https://github.com/weblogixx/generator-react-webpack/tree/rewrite. It uses react-webpack-template as source of the project generation process, so version updates and stuff like that can be done without altering the generator code.

I also wrote some tests for the utility functions (just two or three needed ones) and the generation itself.
However, I build it from scratch because the internals of the current generator where a bit hard to gasp.

Please take a look at it and tell me what you think. I will create a new repository for a flux-enabled version that uses the base generator to provide alt.js support, just to see how easy it can be done.

What do you think about creating an organization for the complete generator packages, so they can be easier maintained? I could also move the template, as well as the 2.0 codebase onto it.

Looking forward to your answer.

**Comment by weblogixx** [comment]
@newtriks: Info: The new generator will only work on node >= 4.0.0. I used arrow functions and stuff like that to create it.

**Comment by newtriks** [comment]
@weblogixx mate, this is amazing work thank you so much! The past three months for me have been consumed with so many things I have been unable to look at this generator, so your work is gratefully appreciated.

Once reviewed and deployed I suggest we maybe propose this generator to the https://github.com/rackt organisation? I don't know how they review potential repos but maybe @ryanflorence could be of assitance to us?

**Comment by weblogixx** [comment]
@newtriks: That would be really nice. There are some things missing currently (as the new readme and stuff), but that should be there in no time. Unit tests for react-webpack:component are there since the last commit, too :)

**Comment by weblogixx** [comment]
@newtriks: Seems like it works with composing, I still have to include support for creating new components but the rest seems to fit quite well. Please have a look at https://github.com/weblogixx/generator-react-webpack-alt for a running configuration.

Did you have time for a look at the new source already? I would like to roll out 2.0 as fast as possible (because the number of requests for 1.0 are still getting more).

**Comment by weblogixx** [comment]
As Version 2 is out now, this feature can now be closed.
