### ISSUE TITLE
'use strict'

### ISSUE THREAD

**Issue by camjc** [newtriks/generator-react-webpack#159]
Is `use strict` necessary or not? Looks like some modules have it and some don't. Wondering what the difference is here and if we can standardize on one or the other.

**Comment by camjc** [comment]
Looks like babel writes use strict for us https://babeljs.io/docs/advanced/transformers/other/strict/
So we can remove it from the generators right?

**Comment by weblogixx** [comment]
Hi @camjc,

strictly speaking, it should not be possible.
However I have the hope that in some time from now we will only need babel from jsx transpilation and not to make our  ES2015 based projects backward compatible.

Therefore I opted to always include it. If you are using linting in editors (like atom esLint) it is also better to have it integrated because the linter does not know use strict gets automatically appended via babel.

**Comment by camjc** [comment]
Cheers. Closing.
