### ISSUE TITLE
Deep module directories don't work as expected

### ISSUE THREAD

**Issue by jemminger** [newtriks/generator-react-webpack#164]
Given this directory tree:

    components
      foo
        index.js
        bar
          index.js

Using babel es6, I would like to do this:

    import Foo from "./components/foo"
    import Bar from "./components/foo/bar"

But it errors with `Module build failed: Error: ENOENT: no such file or directory, open '/Users/jemminger/Development/whatever/components/foo/bar.js'`

The only way I can get it to work is this:

    import Foo from "./components/foo"
    import Bar from "./components/foo/bar/index"

or

    import Foo from "./components/foo"
    import Bar from "./components/foo/bar/"

According to https://nodejs.org/api/modules.html#modules_folders_as_modules I should be able to load the `index.js` file of a directory by default, which happens for `foo` but not `bar`.

This works as expected if I use webpack and babel in a project not generated via generator-react-webpack

**Comment by weblogixx** [comment]
@jemminger: Just looked at this and I do not have this problem with the current version of the generator. What I did:

- Creating a new project with generator-react-webpack
- Creating two new components (yo react-webpack:component foo/index and foo/bar/index)
- Renaming both components (because the filename would be IndeComponent.js instead of index.js)
- Adding both to src/components/Main.js with the import statements above.
=> Both where showing up fine. 

Which version of the generator do you have currently installed? Which node version?

**Comment by jemminger** [comment]
@weblogixx Generator v 2.2.7, node v5.0.0

Was going to post the following (below), but in writing this all out and starting the project up again, it's working like it should :/  Perhaps something got corrupted last time and restarting webpack-dev-server fixed it?  I'll chalk it up to me being a noob

The following seems to be irrelevant now:

----

I'm pretty new to node/webpack/es6 so it's likely I'm just doing something wrong.  Here's my test project for reference: https://github.com/jemminger/react-pages-test

You can see in src/components/run.js the line `import InboxStats from "./inbox/stats/"` - it's throwing that error if I don't use the trailing slash.

I'm running the project via `webpack-dev-server --progress --colors --inline`
