### ISSUE TITLE
react-bootstrap

### ISSUE THREAD

**Issue by Grandiz** [newtriks/generator-react-webpack#169]
Tried to use https://react-bootstrap.github.io/.

In render method simple write < Button bsStyle="link">Link< /Button > and on top of script import {Button} from 'react-bootstrap'; Button appear on page, but unfortunately no style on the btn. No error on browser concole
Have anyone faced to the same problem?

**Comment by sthzg** [comment]
@Grandiz did you add the bootstrap CSS to your page (e.g. as a `<link/>` in `index.html`)?

**Comment by weblogixx** [comment]
Hi @Grandiz,

seems like the react-bootstrap project does ***NOT*** ship with a default bootstrap.css. To quote their website:

- Because many folks use custom Bootstrap themes, we do not directly depend on Bootstrap. It is up to you to to determine how you get and link to the Bootstrap CSS and fonts.
- React-Bootstrap doesn't depend on a very precise version of Bootstrap. Just pull the latest and, in case of trouble, take hints on the version used by this documentation page. Then, have Bootstrap in your dependencies and ensure your build can read your Less/Sass/SCSS entry point.

So in the end, just install bootstrap via npm (```npm install --save bootstrap```) and require the css files to add the css to your component. Note that this will also add the jquery plugins, so you will have to require just the styles (could be something like ```require('bootstrap/dist/css');```, but I dont really know without testing). Hope that helps!
