### ISSUE TITLE
Relay

### ISSUE THREAD

**Issue by stylesuxx** [newtriks/generator-react-webpack#175]
Hey @weblogixx,
I just wanted to ask what your stand on Relay is.

To give some context: I am building myself a stack which looks like this:
* express + passport + graphql as backend via [generator-es6-graphql](https://github.com/stylesuxx/generator-es6-graphql)
* redux + relay + react in the front using this repo for the react part

I saw your [https://github.com/weblogixx/generator-react-webpack-alt](generator-react-webpack-alt) which I wanted to use as a "template" to adapt it to redux.

One of the next steps for me is to get the relay and redux parts up and running, and I was wondering what your stand is on this. Is the relay part something I could add to this generator or would this be something I better place in my "top level" redux generator?

My ultimate goal is then to have a generator like this:
```
generator-my-full-stack-opinion
  generator-my-front-stack-optinion
    generator-react-webpack-redux
      generator-react-webpack
  generator-my-backend-stack-opinion
      generator-es6-graphql
```

I would appreciate some feedback on this.

Ps.: Also summoning @sthzg for his opinion/feedback on generator composition.

**Comment by weblogixx** [comment]
Hi @stylesuxx,

currently you would have to build it the way you describe it (at least roughly):

- First you would have to build a relay generator
- Next, you would build your redux version
- Then, you would throw both together in a third generator.

Currently, the call methods for yeoman scripts do allow to use other generators, but you will have to mimic the filesystem layout (e.g., generator-react-webpack-alt does not extend generator-react-webpack, but for all of generator-react-webpacks options, I have to create dummy folders). Thats unfortunate, but currently there seems no official alternative that I see.

@sthzg did try to fix this with his own implementation, but it was a little hacky (altough, I think it was a good piece of work and this feature ***is*** one that I really miss in yeoman). Maybe something like this should be contributed to yeoman directly?

**Comment by sthzg** [comment]
_a little hacky_ ... is a nice understatement :) I realized that going down that route means eventually rebuilding (a bit of) NPM (a registry, a config format, a network layer for downloading/updating, declaration of compatibility). Of course that makes no sense, so it should either be built on NPM or as @weblogixx says directly into Yeoman. The feature on Yeoman is open to PRs https://github.com/yeoman/generator/issues/867.

Maybe the biggest problem with subgen-composition that I see right now is that the only _easy_ thing to achieve is plugging your standalone-subgens into a foreign generator as long as there is no real composition between them. I think the reason that composition can't work well is because of maintainability. 

As soon as logic is not maintained within one umbrella-project (with an umbrella-test-suite) any update of the host-generator might break composed features in 3rd-party subgens (if these 3rd-party-subgens modify syntax in the core/other subgens in any way it could even damage the system).

The way that Yo handles composition right now prevents this, but it comes at a high cost (in context of the particular use case, not in general).

That said, I think that solving that problem would enable interesting features in the world of starter-kits / boilerplates. Because more often than not you want to change at least one or two components of an otherwise perfect starter kit. And it's not all that difficult to do, but it's that kind of thing that you have to do anytime you start a new project (and to coordinate with updates from the original starter kit).

**Comment by weblogixx** [comment]
I think so, too. However while we have no official support for such a feature, we would still have to do it the way it is done in the alt version I think.

@stylesuxx: Please tell me when you start with your work, would be interested in something like this, too. On the redux part, just tell me when you are ready and I will add a link to the README.

**Comment by stylesuxx** [comment]
This is some good food for thoughts, thank you guys. I will need to break this down in a small test setup, somehow I feel I am still missing a piece to fully understand the problem :-/

@weblogixx I will keep you updated, maybe you can leave this issue open for further discussion.

**Comment by weblogixx** [comment]
@stylesuxx, yes, lets do it like that. Just have a look at generator-react-webpack-alt (the name is waaaay to long :() to see how it is done in the "yeoman way". That means you will need to add some (more or less) useless directories.

However, if you find another way to make things smoother for dependent generators, please contact me and I will happily follow them.

**Comment by weblogixx** [comment]
@stylesuxx: I will close this issue, as the question itself has nothing to do with the generator itself. If you need more input, do not hesitate to open a new issue.
