### ISSUE TITLE
Client-side routing

### ISSUE THREAD

**Issue by petehunt** [newtriks/generator-react-webpack#6]
Would be cool if there was a React router that was in npm installable and was set up out-of-the-box by the generator

**Comment by RobErskine** [comment]
Sorry to comment on such an old issue, but is this `react-router` still part of this generator? I'm not seeing in in the generator command prompts, and I don't see it documented (it's addition on removal) in the changelog.

**Comment by weblogixx** [comment]
Hi @RobErskine,

the generator does not have support for flux or react-router anymore. This was done in version 2.0, because we wanted it to be easier to maintain (see https://github.com/newtriks/generator-react-webpack#changes-in-version-20). For flux frameworks, there are currently at least 2 other generators using generator-react-webpack as base (reflux and alt.js). Both are linked to in the README.

Installing react-router is easy as:

```
npm install --save react-router

// Update run.js:
import { Router } from 'react-router';
import history from '../utils/History.js';

ReactDOM.render(
  <Router history={history}>
    // YOUR ROUTES HERE
  </Router>,
  document.getElementById('app')
);

// Create src/utils/History.js
import { createHistory } from 'history';
export default createHistory();

// Update the main component:
require('reset.css');
require('styles/App.less');

import React from 'react';

class AppComponent extends React.Component {
  render() {
    return (
      <div className="layout">
        {this.props.children}
      </div>
    );
  }
}

export default AppComponent;
```

Hope this helps.

**Comment by RobErskine** [comment]
Thanks @weblogixx, that's great. I didn't realize react-router was part of the flux strip out overall done in 2.0.
