### ISSUE TITLE
Update webpack and react-hot-loader to latest versions

### ISSUE THREAD

**Issue by firstdoit** [newtriks/generator-react-webpack#91]
Newest versions of both packages enables us to `npm link` React components and have hot reload work simultaneously in both child and parent! 

I'll create a PR when I have some time.

Versions I tested with: 

"webpack": "~1.8.4"
"react-hot-loader": "^1.2.5"

**Comment by weblogixx** [comment]
@firstdoit Webpack was updated to 1.10.x some time ago, the hot loader update will be in the next release (I dont think we need a patch right now because the new version does not differ that much from the currently used one).

Therefore, I will close this request (was lying around long enough I think ;)).
